config/routes.rb
CryptDemo::Application.routes.draw do
  root "demo#index"
  resources :demo
end

app/models/demo.rb
class Demo < ActiveRecord::Base
  crypt_keeper :secret_value,
    :encryptor => :aes_new,
    :key => 'fe6f83deb9a8317d0e70c261826d823812ae71b87606ecf8a4',
    :salt => 'fc48bbf9de374448c9e75d31a9075f',
    :encoding => 'UTF-8'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/demo_controller.rb
class DemoController < ApplicationController
  def index
    @demos = Demo.all
  end

  def new
    @demo = Demo.new
  end

  def edit
    @demo = Demo.find(params[:id])
  end

  def create
    demo = Demo.new(demo_params)
    if demo.save
      redirect_to demo_index_path
    else
      flash[:errors] = "An error ocurred when creating demo"
      render :new
    end
  end

  def update
    @demo = Demo.find(params[:id])
    if @demo.update_attributes(demo_params)
      redirect_to demo_index_path
    else
      flash[:errors] = "An error ocurred when updating demo"
      render :edit
    end
  end

private

  def demo_params
    params.require(:demo).permit(:name, :secret_value)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/views/demo/edit.html.erb
<%= form_for @demo, url: demo_url(@demo), method: "PUT" do |f| %>
  <%= f.label :name %><br />
  <%= f.text_field :name %><br />
  <%= f.label :secret_value %><br />
  <%= f.text_field :secret_value %><br />
  <%= f.submit "Save" %>
<% end %>
<br />
<%= link_to "Back to list", demo_index_url %>

app/views/demo/index.html.erb
<h2>Demo list</h2>
<%= link_to "Add new record", new_demo_url %>
<br /><br />
<table width="70%">
  <tr>
    <th>Name</th>
    <th>Secret value</th>
  </tr>
  <% @demos.each do |demo| %>
    <tr>
      <td style="border: 1px solid #ddd"><%= link_to demo.name, edit_demo_url(demo) %></td>
      <td style="border: 1px solid #ddd"><%= demo.secret_value %></td>
    </tr>
  <% end %>
</table>

app/views/demo/new.html.erb
<%= form_for @demo, url: demo_index_url do |f| %>
  <%= f.label :name %><br />
  <%= f.text_field :name %><br />
  <%= f.label :secret_value %><br />
  <%= f.text_field :secret_value %><br />
  <%= f.submit "Save" %>
<% end %>
<br />
<%= link_to "Back to list", demo_index_url %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CryptDemo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>